### ISSUE TITLE
ntopng local host names

### ISSUE THREAD

**Issue by Azhdar1990** [synfinatic/netflow2ng#12]
Hello.
First of all, thank you for creating netflow2ng.
Now i started receive flows to ntopng.
But unfortioantly a can't receive name of my local hosts.
There are ip adress instead of name of local host.
I configured dns-mode in ntopng.conf file (i used 1, 2 and 3) then restarted ntopng but it didn't help.

I get flows from mikrotik  (trafic flow v9 and port 2055)

Please could you help and tell how can i get host names instead of ip addresses?
Thank's in advance.

**Comment by synfinatic** [comment]
Unless I'm missing something, the netflow protocol doesn't support hostnames/FQDN.  It just does IP addresses.  Hence, I'm not sure what you're asking is possible.  Have you talked to the ntopng people and asked them?

**Comment by Azhdar1990** [comment]
I've find problem. 
To get names of hosts, there must be PTR records in DNS server . 
Otherwise it is not possible to get  host names.
