### ISSUE TITLE
Which version of Ntopng work well with current Netflow2ng

### ISSUE THREAD

**Issue by tlsalex** [synfinatic/netflow2ng#14]
Hello Sir,

I want to try this project , and I want to know which version of Ntopng I should use to avoid the unexpected error on latest Ntopng. I also see some compile error report in closed Issue. Could you please suggest which OS (Fedora , Centos , Debian ?) and which version I should use to avoid unexpected compile error.

Thank you.

**Comment by synfinatic** [comment]
I use Ubuntu and the latest ntopng package available.  No idea what "unexpected error" you're talking about so can't speak more to that.

I can only guess what "compile error report in closed issue" you're referring to.  I would say read the comments and don't do what those people were doing.  Easiest thing to do is build and install netflow2ng on the same box you install ntopng.
