### ISSUE TITLE
Not working anymore with Netflow v9?

### ISSUE THREAD

**Issue by dijey099** [synfinatic/netflow2ng#22]
I pulled the docker image and run it with `docker run <image id>` but no flow is collected nor exported

**Comment by synfinatic** [comment]
if that's literally what you run, then yeah, it definitely won't work.  Perhaps you should look at the sample [docker-compose](https://github.com/synfinatic/netflow2ng/blob/main/docker-compose.yaml) file?

**Comment by dijey099** [comment]
@synfinatic thanks for reply... It works now
Can you please explain the way you convert Netflow packets into ntop/nprobe packets? 🙏🏽
I searching a way to replace nprobe with a python script.

I can get Netflow packets using socket as follow:
`sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
print("Miandry packet...")
sock.bind(("0.0.0.0", 2055))
payload, router = sock.recvfrom(4096)
print(payload)`

And get output like that:
`b'\x00\t\x00\x18\x08\xcc\x8c\xccc\x85\xd3\xe9\x00\x08\xfa\x02\x00\x00\x00\x00\x01\x05\x00\xec\xc0\xa8\xb0\x12\x8e\xfa\xcb\xea\x9ax\x86\x81\xdb\x00\x01\xbb\x1b\x00\x1a\x00\x05\x00\x00\x00\x0c\x00\x00\x08\r\x08\xccB<\x08\xccQ\x88\x06\x00\xf0\x00\x00\x00\x10V\xca\r%\xd4\xe8jd.\xbe\xac\x08\x00\xff\xc0\xa8\xaf;\x97eA\x8c\x9ax\x86\x81\xa5z\x01\xbb\x1b\x00\x1c\x00\x05\x00\x00\x00\n\x00\x00\x10.\x08\xcc)\xf8\x08\xccQ\x94\x06\x00\xf1\x00\x00\x00\x10V\xca\r%\xd44\xb9\x8d`v\xbf\x08\x00\xff\x9ax\x85]\xc0\xa8\xb1\x1c\x00\x00\x00\x00\x01\xbb\xd2\xfb\x1a\x00\x05\x00(\x00\x00\x00\x05\x00\x00\x04K\x08\xccP\x8c\x08\xccQ\xb4\x06\x00\xf0\x00\x00\x00\x10V\xca\r%\xd5\x1c\xea\x1bj\xe8\x89\x08\x00\xff\xc0\xa8\xb0l\x9d\xf0\x15!\x9ax\x86\x81\xd0\xde\x01\xbb\x18\x00\x1a\x00\x05\x00\x00\x00\x02\x00\x00\x00\x91\x08\xccQ\x98\x08\xccQ\xb8\x06\x00\x81\x00\x00\x00\x10V\xca\r%\xd4B\x05\xee>uA\x08\x00\xff\x01\x04\x00<\xc0\xa8\xae(4m8q\x9a~s\x01\xc5\xb8\x01\xbb\x10\x00\x1e\x00+\x00\x00\x00\x01\x00\x00\x00)\x08\xccQ\xa4\x08\xccQ\xa4\x06\x00\x10V\xca\r%\xd4\x18^\x0fT\xe6\x06\x08\x00\xff\x00\x00\x01\x07\x004\x02\x14\xb2Q\xc0\xa8\xb2\x13\x00\x00\x00\x00\x00P\xa0\xce\x12\x00+\x00\x18\x00\x00\x00\x01\x00\x00\x00<\x08\xccQ\xc4\x08\xccQ\xc4\x06\x00\xf1\x00\x00\x00\x08\x00\xff\x00\x00\x01\x05\x00@\xd8:\xd3\xce\xc0\xa8\xb0\x12\x00\x00\x00\x00\x01\xbb\xda\xfd\x1b\x00\x05\x00\x1a\x00\x00\x00\x1c\x00\x00\x10\xbb\x08\xcc64\x08\xccQx\x06\x00\xf8\x00\x00\x00\x10V\xca\r%\xd5\x1c\xea\x1bj\xe8\x89\x08\x00\xff\x00\x00\x01\x04\x00<\x8e\xfa\xc9*\xc0\xa8\xb1\x1c\x00\x00\x00\x00\x01\xbb\xcf\xb4\x18\x00\x05\x00(\x00\x00\x00\x10\x00\x00\x04\xee\x08\xccD\xfc\x08\xccQ\x88\x06\x00\x10V\xca\r%\xd5\x1c\xea\x1bj\xe8\x89\x08\x00\xff\x00\x00\x01\x05\x00\xec\xc0\xa8\xb0\x12\xd8:\xd3\xce\x9ax\x86\x81\xda\xfd\x01\xbb\x1b\x00\x1a\x00\x05\x00\x00\x00\x19\x00\x00K\xd3\x08\xcc5\x8c\x08\xccQx\x06\x00\xf0\x00\x00\x00\x10V\xca\r%\xd4\xe8jd.\xbe\xac\x08\x00\xff\xc0\xa8\xafr\x11\xf8\xd7\x02\x9ax\x86\x81\xfe\xe2\x01\xbb\x1b\x00\x1c\x00\x05\x00\x00\x00\n\x00\x00\x107\x08\xcb\xa7\xf4\x08\xccQ\xb4\x06(\xf1\x00\x00\x01\x10V\xca\r%\xd4>\xef@"|\xbc\x08\x00\xff\xc0\xa8\xad\xd3"\xff~\x9b\x9a~s\x01\x98v\x00P\x1b\x00\x14\x00+\x00\x00\x00\x07\x00\x00\x10\xc1\x08\xccN\xfc\x08\xccQ\x94\x06\x00\xf1\x00\x00\x00\x10V\xca\r%\xd4\x00\x0c)\x18\x86V\x08\x00\xff\xc0\xa8\xb0\x12\x8e\xfb%\xa3\x9ax\x86\x81\xda\xfc\x01\xbb\x1b\x00\x1a\x00\x05\x00\x00\x00\x0c\x00\x00\x08\xb9\x08\xcc)\xc8\x08\xccQx\x06\x00\xf0\x00\x00\x00\x10V\xca\r%\xd4\xe8jd.\xbe\xac\x08\x00\xff\x01\x04\x00<\xc0\xa8\xb1\x1c\x8e\xfa\xc9*\x9ax\x86\x81\xcf\xb4\x01\xbb\x18\x00(\x00\x05\x00\x00\x00\t\x00\x00\n@\x08\xccE\x00\x08\xccQ\x8c\x06\x00\x10V\xca\r%\xd4\xe8*\xea)\x18\xc8\x08\x00\xff\x00\x00\x01\x07\x0046\xf6\x9e\x9e\xc0\xa8\xab\x0b\x00\x00\x00\x00\x01\xbb\xf8\x95\x19\x00+\x00"\x00\x00\x00\x05\x00\x00\x01!\x08\xcc\x16\x94\x08\xccQ\xa4\x06(\x88\x00\x00\x00\x08\x00\xff\x00\x00\x01\x05\x00@\xd8:\xd3\xce\xc0\xa8\xb2\x0e\x00\x00\x00\x00\x01\xbb\xcc\xc0\x12\x00\x05\x00\x18\x00\x00\x00\x01\x00\x00\x004\x08\xccQ\xd8\x08\xccQ\xd8\x06\x00\xf0\x00\x00\x00\x10V\xca\r%\xd5\x1c\xea\x1bj\xe8\x89\x08\x00\xff\x00\x00\x01\x02\x000\x8e\xfb%.\xc0\xa8\xab\r\x00\x00\x00\x00\x01\xbb\xe8\xe4\x18\x00+\x00"\x00\x00\x00\x0f\x00\x00\x07G\x08\xcc>\xcc\x08\xccQ\xe0\x06(\x08\x00\xff\x00\x00\x01\x05\x00x\xc0\xa8\xb1\x1c\x9ax\x85]\x9ax\x86\x81\xd2\xfb\x01\xbb\x1a\x00(\x00\x05\x00\x00\x00\x06\x00\x00\x07E\x08\xccP\x88\x08\xccQ\xec\x06\x00\xf0\x00\x00\x00\x10V\xca\r%\xd4\xe8*\xea)\x18\xc8\x08\x00\xff\xc0\xa8\xb2%\x08\xdb\xc3\xda\x9a~s\x01\xa5\xc2\x01\xbb\x1b\x00\x18\x00+\x00\x00\x00\t\x00\x00\x08m\x08\xccH\xcc\x08\xccQ\xec\x06\x00\xf1\x00\x00\x00\x10V\xca\r%\xd4"\x81\x88\xd1\xa1q\x08\x00\xff\x01\x07\x004\xac\xd9\x12.\xc0\xa8\xae.\x00\x00\x00\x00\x01\xbb\xca\x12\x10\x00+\x00\x1e\x00\x00\x00\x01\x00\x00\x004\x08\xccR\x0c\x08\xccR\x0c\x06\x00\x88\x00\x00\x00\x08\x00\xff\x00\x00\x01\x05\x00@\xd8:\xd3\xce\xc0\xa8\xb2\x0e\x00\x00\x00\x00\x01\xbb\xcc\xbe\x12\x00\x05\x00\x18\x00\x00\x00\x01\x00\x00\x004\x08\xccQ\xd8\x08\xccQ\xd8\x06\x00\xf0\x00\x00\x00\x10V\xca\r%\xd5\x1c\xea\x1bj\xe8\x89\x08\x00\xff\x00\x00\x01\x04\x00p\xc0\xa8\xaf<\xc0\xa8\xad\xe8\x00\x00\x00\x00\xc5q\x005\x00\x00\x1c\x00\x14\x00\x00\x00\x01\x00\x00\x00R\x08\xccR \x08\xccR \x11\x00\x10V\xca\r%\xd4\\\xe0\xc5\xc6\x90\xda\x08\x00\xff\xc0\xa8\xae\x17l\xb1\x0fm\x9a~s\x01\xe2\xd4\x01\xd1\x18\x00\x1e\x00+\x00\x00\x00\x08\x00\x00-\x00\x08\xcc\x14\x98\x08\xccR\x00\x06\x00\x10V\xca\r%\xd4\xdcS`\xee\xb0\xf6\x08\x00\xff\x01\x07\x004\x08\xdb\xc3\xda\xc0\xa8\xb2%\x00\x00\x00\x00\x01\xbb\xa5\xc2\x1b\x00+\x00\x18\x00\x00\x00\x07\x00\x00\x03\xdc\x08\xccJ\x94\x08\xccQ\xe4\x06(\xf0\x00\x00\x00\x08\x00\xff\x00\x00\x01\x04\x00<\xc0\xa8\xad\xea\xd0C\xdc\xdc\x9ax\x86\x81\xc3F\x005\x00\x00\x14\x00\x05\x00\x00\x00\x01\x00\x00\x00]\x08\xccR0\x08\xccR0\x11\x00\x10V\xca\r%\xd4\x00PV\xbf\xcb\xab\x08\x00\xff\x00\x00'`

I also captured packets from your Go script and have the output like that:
`[b'flow\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01A\x00\x00\x06\xc2', b'{"10":30,"11":53,"12":"xxx.xxx.xxx.xxx","14":5,"15":"xxx.xxx.xxx.xxx","16":0,"17":0,"21":1669707312,"22":1669707312,"23":62,"24":1,"29":0,"30":0,"32":0,"4":17,"44":0,"45":0,"5":0,"52":0,"54":0,"58":0,"59":0,"6":0,"60":4,"61":1,"7":64333,"8":"xxx.xxx.xxx.xxx","80":"00:00:00:00:00:00","81":"xxx:xxx:xxx:xxx","88":0,"89":0}']`

What is exactly the item(0) of this list and the item(1) ?

**Comment by dijey099** [comment]
Hello Aaron

Can you please help me? 🙏🏽

Le mar. 29 nov. 2022 à 08:29, Aaron Turner ***@***.***> a
écrit :

**Comment by synfinatic** [comment]
If you want to understand how my code works, I would recommend you read my code.  That would be by far the most accurate way to convey the process.
