### ISSUE TITLE
Huawei IP netstream

### ISSUE THREAD

**Issue by gleberrl** [synfinatic/netflow2ng#29]
when i use a huawei ne40 to export netflow v9 data to netflow2ng i don't have the correct information.
on an interface with approximately 5gb of traffic it is displayed as if it had only 5mbps of traffic.

thanks

In Mikrotik router this information are ok

**Comment by synfinatic** [comment]
netflow2ng doesn't "display" traffic.  Perhaps this is a bug in your ne40 or the software trying to interpret the netflow data it sends?

**Comment by gleberrl** [comment]
Hi,I tried to send traffic from a ne40 and a ne20 to netflow2ng and display it in ntopng, but in none of these cases was I successful. I was successful when my origin was a mikrotik. Can I debug in netflow2ng?Em 2 de jun. de 2023 15:49, Aaron Turner ***@***.***> escreveu:
netflow2ng doesn't "display" traffic.  Perhaps this is a bug in your ne40 or the software trying to interpret the netflow data it sends?

**Comment by synfinatic** [comment]
if It works with a mikrotik then sounds like there is a bug in the ne40/ne20?  Have you contacted Huawei?

Honestly, you've provided no useful information, so I don't know what you want me to do?

**Comment by gleberrl** [comment]
It´s possible change sampling rate on netflow2ng?

**Comment by synfinatic** [comment]
There is no sampling rate in netflow2ng to change.

**Comment by fangkun200** [comment]
The default sampling rate of ne40 is 1000, which may be the cause. You need to process the sampled data.
