### ISSUE TITLE
More explanation on how to use

### ISSUE THREAD

**Issue by kx001001** [synfinatic/netflow2ng#4]
Very glad to see you created this project, I have same situation and commercial nProbe has 25000 flows limitation, I can not use this for my home router since it will reach out it limitation in 30min.

Would you give more information how to utilize these codes?

**Comment by synfinatic** [comment]
clone the git repo.  run `make` followed by `netflow2ng -help` (the netflow2ng binary will be in the `dist` directory

**Comment by kx001001** [comment]
Sorry to borther you again. I tried to compile the codes and getting following errors. Does that mean I should manually fix the dependency or adjust codes ?

==============

root@UBUNTU_18:/mnt/ubuntu/netflow2ng-master# go version                                                               
**go version go1.10.4 linux/amd64**                                                                                        
root@UBUNTU_18:/mnt/ubuntu/netflow2ng-master# make                                                                     
mkdir -p dist/                                                                                                         
go build -ldflags '-X main.version= -X main.buildinfos=(2020-04-28T08:14:07+0000)' -o dist/netflow2ng--linux-x86_64 cmd
/netflow2ng/netflow2ng.go                                                                                              
cmd/netflow2ng/netflow2ng.go:7:2: cannot find package "github.com/cloudflare/goflow/v3/utils" in any of:               
        /usr/lib/go-1.10/src/github.com/cloudflare/goflow/v3/utils (from $GOROOT)                                      
        /root/go/src/github.com/cloudflare/goflow/v3/utils (from $GOPATH)                                              
cmd/netflow2ng/netflow2ng.go:13:2: cannot find package "github.com/prometheus/client_golang/prometheus/promhttp" in any
 of:                                                                                                                   
        /usr/lib/go-1.10/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOROOT)                    
        /root/go/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOPATH)                            
cmd/netflow2ng/netflow2ng.go:8:2: cannot find package "github.com/sirupsen/logrus" in any of:                          
        /usr/lib/go-1.10/src/github.com/sirupsen/logrus (from $GOROOT)                                                 
        /root/go/src/github.com/sirupsen/logrus (from $GOPATH)                                                         
cmd/netflow2ng/netflow2ng.go:9:2: cannot find package "github.com/synfinatic/netflow2ng/transport" in any of:          
        /usr/lib/go-1.10/src/github.com/synfinatic/netflow2ng/transport (from $GOROOT)                                 
        /root/go/src/github.com/synfinatic/netflow2ng/transport (from $GOPATH)                                         
Makefile:35: recipe for target 'dist/netflow2ng--linux-x86_64' failed                                                  
make: *** [dist/netflow2ng--linux-x86_64] Error 1

**Comment by synfinatic** [comment]
go 1.10 is really really old.   Upgrade to 1.14.2

**Comment by kx001001** [comment]
> go 1.10 is really really old. Upgrade to 1.14.2

yes, you are correct. Then I updated to latest ubuntu version 20.04 and got go 1.13.8 installed with default apt tool, eventually everything gets fine.

In additional, 
a. libzmq must be manually compiled and install due to some reasons, otherwise it will say can't find libzqm.pc .
b. libzmq5 is required for new complied program, "apt install libzmq5" to get it installed in ubuntu

Again, thank you for the support.
