### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kx001001** [synfinatic/netflow2ng#8]
Hello Sir, I can run the program successfully on my compiling machine, but I got the below error message when I move the executable file to another machine. Any idea on this? 

-------

root@UBUNTU_18:/mnt/ubuntu/netflow2ng-master/dist# ./netflow2ng--linux-x86_64
INFO[0000] Starting netflow2ng
**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7cd9eb]**

goroutine 1 [running]:
github.com/pebbe/zmq4.(*Context).NewSocket(0x0, 0x1, 0xc000099130, 0xc0000d0c00, 0x8a87e0)
        /root/go/pkg/mod/github.com/pebbe/zmq4@v1.0.0/zmq4.go:834 +0x3b
github.com/synfinatic/netflow2ng/transport.StartZmqProducer(0x8cbabc, 0xc, 0x8c9086, 0x4, 0x9742e0, 0xc00010a460, 0xc0000d7df8, 0x2d4b439a, 0xf9a6cd421a4e21ad)
        /mnt/ubuntu/netflow2ng-master/transport/zmq.go:105 +0xc7
github.com/synfinatic/netflow2ng/transport.StartZmqProducerFromArgs(...)
        /mnt/ubuntu/netflow2ng-master/transport/zmq.go:133
main.main()
        /mnt/ubuntu/netflow2ng-master/cmd/netflow2ng/netflow2ng.go:78 +0x243

**Comment by synfinatic** [comment]
something important is different between the two boxes? same version of ubuntu?  do you have libzmq installed on the machine you're running netflow2ng?  those would be the things I look for first.  you may find better luck running `make package` to build the debian package and installing that instead of the binary.

**Comment by kx001001** [comment]
I moved this binary file from vmware virtual machine of compiling environment to docker resides in another box, from ubuntu 20.04 to ubuntu 16.04, libzmq is installed at both ends. Eventually I get it running after re-compiling in docker afterwards by installing all set of compiling tools and source codes on ubuntu 16.04 @ docker. 

BTW, how to run multiple instances of netflow2ng on same machine ? the case here is I have 3 routers and need to collect flows from them, I plan to run multiple instance to receive netflow from these routers respectively, but the executable file is not allow to do that with below message(tcp 8080 is binded).

![Image 2](https://user-images.githubusercontent.com/48275131/80569531-b3069000-8a2b-11ea-8d9e-33ff886e02b1.png)

**Comment by synfinatic** [comment]
Yeah, building on 20.x and running on 16.x is always going to be challenging.  Lots of things change which can make things not work.

Anyways, you shouldn't need to run multiple copies of netflow2ng.  Just configure all 3 routers to send their netflow to the single netflow2ng collector which will then pass it along to ntopng.

That said, the error message is for tcp/8080.  If you look in the help (you included it in your error message) it will tell you how to change the port.

**Comment by synfinatic** [comment]
Haven't seen a follow up in a long time and the error appears to be a portability issue due to building & running on different systems.
